### ISSUE TITLE
No web optimisation

### ISSUE THREAD

**Issue by iipranavii** [vinitop/workshop_team3#10]
Idle game is taking up around 50%CPU utilization.
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/67915580/201035146-383a82b1-bd1d-4f75-b866-ea99f6a26200.png">

**Comment by vinitop** [comment]
This issue is not with the application. It might be some other process from windows.
![image](https://user-images.githubusercontent.com/72563220/201190084-168bbabc-1cae-4abf-9bd1-0c894fcd06f2.png)
