### ISSUE TITLE
Return to home page

### ISSUE THREAD

**Issue by ravanpreet-kaur** [vinitop/workshop_team3#2]
Selecting Player 1, it displays a message that a1 is sick, and try playing with a friend, but there's no option to return to the default home page from there. 

<img width="674" alt="image" src="https://user-images.githubusercontent.com/73405757/201016479-777b772c-bc8d-4b7d-9711-f2aabf67ad44.png">

**Comment by vinitop** [comment]
Currently this is part of our design.

**Comment by iipranavii** [comment]
Can you please elaborate, how non-functional website is a design choice?

**Comment by vinitop** [comment]
Player 1 option is now fully functional and live.
![image](https://user-images.githubusercontent.com/72563220/201189284-7a95507a-9090-4e63-909e-3c351772a66d.png)
