### ISSUE TITLE
Save Game

### ISSUE THREAD

**Issue by ravanpreet-kaur** [vinitop/workshop_team3#4]
Saving a game doesn't display a message that the game is saved

<img width="650" alt="image" src="https://user-images.githubusercontent.com/73405757/201017426-07dc11a5-fa3d-43f7-aa23-cb438f1806dc.png">

**Comment by vinitop** [comment]
We are working  on it . But still the game get saved in browser.

**Comment by vinitop** [comment]
Issue Fixed.
![image](https://user-images.githubusercontent.com/72563220/201188344-b677d4e2-54e8-47d1-9816-6803652d814b.png)
