### ISSUE TITLE
Load Game

### ISSUE THREAD

**Issue by ravanpreet-kaur** [vinitop/workshop_team3#6]
It's not prompting any message, when the user selects the Load Game button without saving any game initially.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/73405757/201018726-717b86e6-b8cb-4be7-b15d-5ec0f6bd8510.png">

**Comment by vinitop** [comment]
As the game is not saved yet and we are storing it in browsers local storage. Load option won't show any response.
