### ISSUE TITLE
No Navigation option after the game ends

### ISSUE THREAD

**Issue by iipranavii** [vinitop/workshop_team3#8]
After the game ends, there is no option to go back or navigate to another game mode.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/67915580/201028222-a4aa2b15-d497-47fd-bb12-b165c1a41fce.png">

**Comment by vinitop** [comment]
Player can reload the page to restart a new game or to start a saved game. In future build we will add more navigation options throughout the application.
