### ISSUE TITLE
No option to forfeit the game

### ISSUE THREAD

**Issue by iipranavii** [vinitop/workshop_team3#9]
The player can't end the match while in game without refreshing the game
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/67915580/201029743-9b8ee93c-fbf0-4fde-86be-8564fcabb00f.png">

**Comment by vinitop** [comment]
Issue acknowledged. Our team is working on it.

**Comment by vinitop** [comment]
Check the latest build. We had done some modification in UI.
